DROP TABLE tbclientes;
DROP TABLE tbavaliacoes;

alter table tbavaliacoes drop foreign key tbavaliacoes_ibfk_1;
alter table tbavaliacoes drop foreign key tbavaliacoes_ibfk_2;

CREATE DATABASE IF NOT EXISTS vitrine_virtual_todo6;

USE vitrine_virtual_todo6;

CREATE TABLE IF NOT EXISTS tbProdutos
(ID_PRODUTO INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(100),
DESCRICAO VARCHAR(150),
ID_FORNECEDOR INT,
CATEGORIA VARCHAR(50),
TAMANHO VARCHAR(10),
PRECO FLOAT,
SUSTENTAVEL BIT,
QTD_ESTOQUE SMALLINT,
PRIMARY KEY (ID_PRODUTO)
);

CREATE TABLE IF NOT EXISTS tbClientes
(CPF VARCHAR(11) NOT NULL,
NOME VARCHAR(50),
SOBRENOME VARCHAR(50),
NACIONALIDADE VARCHAR(150),
DATA_NASCIMENTO VARCHAR(50),
PRIMARY KEY (CPF)
);

CREATE TABLE IF NOT EXISTS tbAvaliacoes
(ID_AVALIACAO INT NOT NULL AUTO_INCREMENT,
CPF VARCHAR(11),
ID_PRODUTO INT,
TITULO VARCHAR(50),
DATA_AVALIACAO DATE,
COMENTARIO VARCHAR(200),
NOTA SMALLINT,
PRIMARY KEY (ID_AVALIACAO),
FOREIGN KEY (CPF) REFERENCES tbClientes(CPF),
FOREIGN KEY (ID_PRODUTO) REFERENCES tbProdutos(ID_PRODUTO),
CHECK (NOTA>=1 AND NOTA<=5)
);